### ISSUE TITLE
missing regions

### ISSUE THREAD

**Issue by sunkid** [equalpants/pigmap#18]
After the update to handle the region format, I re-generated my entire converted map. This resulted in missing regions with strange borders: http://i.imgur.com/c1G4M.png . The icons are warp points, showing that these missing regions where indeed explored. Visiting them again, will add the missing map areas with the next incremental map update.

**Comment by equalpants** [comment]
It looks like you performed an incremental update on an empty map (or portion of a map).  Do any of the following describe what you did?
1. deleted existing map, tried to run incremental update on empty map dir but failed with "pigmap.params not found", manually placed a new copy of pigmap.params in the output dir, successfully ran incremental update on top of empty map
2. converted existing map images to some format other than PNG, then ran incremental update on map
3. ran an incremental update with an incomplete regionlist--i.e. previous map was created at time X, some new territory was explored between times X and Y, some more new territory was explored between Y and Z, and the regionlist you supplied covered only those regions modified between times Y and Z

If none of these apply, please provide the command line that you used, and the console output from pigmap.

**Comment by sunkid** [comment]
Yeah, no, I did none of that.

I did

```
\rm -rf ../../../maps/pigmap/{0,1,2,3,4}*
./pigmap -B 6 -T 1 -Z 10 -i /mnt/ram/world/ -o ../../../maps/pigmap -g ../terrain/ -h 4
```

and got no errors. Afterwards, as described, I ran incremental updates.

Just re-did the map again (thanks to pigmap's speed not a big deal! :) ) and it looks normal now. Could it be that the region conversion was simply not finished? I did issue a 'save-all' but didn't stop the server before doing the first run.

**Comment by equalpants** [comment]
Hmm, if the server was running, that might explain it.  The very first step of a full render is determining which tiles need to be drawn, which means opening up all the regions and seeing which chunks actually exist; any tiles touched by an existing chunk are marked for rendering.  So if pigmap can't open one of the region files because the server has locked it, any tiles that touch only that region won't be drawn.

For some reason I didn't put in an error message for that; I'll add one now, so if that's the right explanation, you'll see some "can't open region file X" errors if it happens again.
