### ISSUE TITLE
Pigmap crashes my server on every map update

### ISSUE THREAD

**Issue by nitroxygen** [equalpants/pigmap#24]
I have pigmap to update every day at 2:20 in the morning when no one is on. For some reason every morning when i have to wake up i have to restart the server. Should pigmap be doing this and now can i stop it from doing this.
This is what i use to do the update:

15 2 \* \* \* rsync -r -t -v /home/itsryan/minecraft/world /home/itsryan/input > /home/itsryan/change
20 2 \* \* \* tail -n +3 /home/itsryan/change > /home/itsryan/changes
22 2 \* \* \* /home/itsryan/pigmap/pigmap -i /home/itsryan/input/world -o /home/admin/public_html/output -g /home/itsryan/pigmap -r /home/itsryan/changes -x -m /home/itsryan/pigmap/

my server has 2gb and im also running my website off of it, i dont think it will effect anything though, it should not crash.

**Comment by equalpants** [comment]
1. Can you verify that pigmap is causing it?  If you run pigmap yourself a few times, while you're observing it, does the server crash?
2. What does the server's crash log say?
3. What is the peak memory usage when pigmap (and everything else) is running?  What OS is this on, and how big is your swap file?

**Comment by nitroxygen** [comment]
I can verify that it crashes the minecraft server every time it runs. When the minecraft server goes down I check the logs and all it says is nothing there is no errors of any kind. The peak memory is 2097152k at all times i dont know why it uses 98%cpu and 10% memory when running. I am on CentOS 5. when i use the TOP command in terminal my swap total is at 0k at all times.

**Comment by equalpants** [comment]
Do you know how much memory the Minecraft server is using at the time?  With 2GB and no swap, it could definitely be running out of memory and aborting.  Since pigmap is running on a backup of the world (and therefore not touching any files actually used by the server), there's not really much it could possibly do to the server, other than compete for resources.

One way to check would be to try running some other program that needs a similar amount of memory (200MB at least) for a similar amount of time, and see if that brings down the server too.
