### ISSUE TITLE
Blocksize 8 + Tilesize 256*256

### ISSUE THREAD

**Issue by nidefawl** [equalpants/pigmap#40]
Hi,
I just realized how much faster map loading works when using block-size 4, tilesize 1 which results in 256*256 png-tiles.  But the map does not look half as good as a block-size 8 rendering.

Unfortunately the minimum tilesize for block-size 8 is 512*512 which loads quite slow.

I wonder if there are any plans to support outputting multiple base-tiles per chunk.
If not, any hints on what to change/where to start would be appreciated.

**Comment by equalpants** [comment]
Hello,

I don't have any plans to change that at the moment, unfortunately.  It probably wouldn't be an outrageous amount of work, but there would be a lot of changes all over the code.  The main reason for making a tile one chunk wide is just that it simplifies the math.

The place to start looking would be in the comments at the top of map.h describing the coordinate systems.  What you're proposing is to remove the condition that T must be an integer, and let it be = 1/2 instead.  If you look at the places where T is used you can see that most of the time it appears with a constant 64, so those terms would all still be integers and work fine, but some places would need more thought--TileIdx::baseChunk for example.  The TileBlockIterator in render.cpp would probably also need some work.

It might actually be easier to split the base tiles up manually as a post-processing step after pigmap runs, and then rebuild the higher-level tiles--I think ImageMagick would probably be able to handle that.  If you wanted to try that then you could also save some computation by modifying pigmap so that it _only_ draws/saves the base tiles, which wouldn't be hard at all.

Hope that helps,

Michael Nelson
yep.
